name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.7.1
  path_provider: ^2.0.9
  http: ^1.1.0
  google_fonts: ^5.1.0
  flutter_share: ^2.0.0
  hooks_riverpod: ^2.4.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.13
  flutter_hooks: ^0.20.1
  uuid: ^3.0.6
  mockito: ^5.1.0
  agora_uikit: ^1.3.6
  flutter_local_notifications: ^9.6.1
  google_maps_flutter: ^2.1.8
  flutter_signin_button: ^2.0.0
  camera: ^0.10.0+1
  path: ^1.8.1
  #pay: ^1.0.8
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1
  freezed:
  json_serializable: ^6.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Anita.jpeg
    - assets/images/a.png
    - assets/images/google.png
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
